teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
  - name: openvtc-admins
    maintainers:
      - geoffturk
      - stormer78
  - name: openvtc-maintainers
    maintainers:
      - geoffturk
      - stormer78
    members:
      - vthwang
  - name: probablistic-sampling-members
    maintainers:
      - stormer78
    members:
      - DenisPopov15
repositories:
  - name: governance
    teams:
      lf-staff: maintain
      openvtc-admins: maintain
    visibility: public
  - name: dtg-credentials
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: openvtc
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: verifiable-trust-infrastructure
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: vti-setup
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: wiki
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: vta-browser-plugin
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: vti-didcomm-js
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: rp-sdk-js
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: vta-mobile-agent-ios
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: vti-push-gateway
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: verifiable-git-infrastructure
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
    visibility: public
  - name: probablistic-sampling-for-connection-vcs
    teams:
      openvtc-admins: admin
      openvtc-maintainers: maintain
      probablistic-sampling-members: write
    visibility: public
